# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LastUpdateState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_RUN', 'Not run'), ('FAIL   ', 'Failed'), ('SUCCESS', 'Succeeded'), ('RUNNING', 'Running')], default='NOT_RUN', max_length=7)),
                ('num_processed', models.IntegerField(default=0)),
                ('num_total', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_RUN', 'Not run'), ('FAIL   ', 'Failed'), ('SUCCESS', 'Succeeded'), ('RUNNING', 'Running')], default='NOT_RUN', max_length=7)),
                ('num_processed', models.IntegerField(default=0)),
                ('num_total', models.IntegerField(default=0)),
                ('started_datetime', models.DateTimeField()),
                ('ended_datetime', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lastupdatestate',
            name='update_result_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UpdateResult'),
        ),
        migrations.AddField(
            model_name='banner',
            name='update_result_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UpdateResult'),
        ),
    ]
