# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateresult',
            name='ended_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
